### ISSUE TITLE
Bug nth-child selector

### ISSUE THREAD

**Issue by DotMaui** [radkovo/jStyleParser#108]
If I parsed this rule:

`.ui-autocomplete li div.blocco-arrivo span:nth-child(1) {
    font-size: 12px;
    color: #888
}`

 and I go to retrieve the selector the result is the following:

`.ui-autocomplete li div.blocco-arrivo span:nth-child(\31)`

With a **\3** that shouldn't be there.

Here the complete example:
[dotmaui.com/pastebin/p4W7lzaW](https://dotmaui.com/pastebin/p4W7lzaW)

**Comment by radkovo** [comment]
Thanks for reporting this, there was some excessive escaping included. I fixed that and I hope that it won't cause other problems.

**Comment by DotMaui** [comment]
thank you
