### ISSUE TITLE
Update ANTLR version

### ISSUE THREAD

**Issue by azinemanas** [radkovo/jStyleParser#118]
I personally have the problem of using the library with a new version of spring boot (Hibernate particularly).
That version depends on ANTLR 4.10.1 but the grammar version is incompatible with version 4.5.3 the current version.
I compiled a custom jStyleParser with version 4.10.1 and use with CCSBox in my application without problems.

**Comment by Zeemee7** [comment]
Created a merge request for that: #119

**Comment by radkovo** [comment]
Thanks for the PR, merged. I also accepted the Java update to version 11. However, it seems that the current LTS version is 25 so the question is: Is there any reason to stick with version 11?

**Comment by radkovo** [comment]
Included in the new 4.0.1 release; closing.
