### ISSUE TITLE
Ability to set a callback for network connections

### ISSUE THREAD

**Issue by hrj** [radkovo/jStyleParser#14]
### Goal
Currently, jStyleParser starts fetching from the network whenever it sees `@import` rules.

However, in gngr, we need network connections to be handled in the browser core. Reasons:
* the browser maintains a network cache which can be utilised for the CSS requests
* the browser has a request manager to control which network requests are allowed
* the browser needs to maintain separate connection pools for separate trust zones

### Ideas
I initially thought that it would be best if jStyleParser only did the parsing and returned `@import rules` in the AST. The browser would initiate the request and call the parser again.

However, I think a simpler way would be to pass a callback function to jStyleParser which the parser can call whenever it needs to make a network request. The actual request will then be processed/filtered/logged in the browser and the response will be handed back to the parser.

An example API could be:
```java
public Interface NetworkProcessor {
  // fetches a URL and returns the response as a String.
  // On error, returns null
  public String fetch(URL url);
}

public Class CSSParserFactory {
  public parse(String css, blah blah, NetworkProcessor processor) {
  }
}
```

If you like, we could also probably use something like `java.net.URLStreamHandler`, but I haven't fully thought about that interface.

**Comment by radkovo** [comment]
Yes, current implementation is very simple and I was planning to improve it as soon as someone needs it.

Regarding the interface: we have already something similar in CSSBox. The basic interface is defined by the [DocumentSource](https://github.com/radkovo/CSSBox/blob/master/src/main/java/org/fit/cssbox/io/DocumentSource.java) abstract class. I mean we could create a compatible interface in jStyleParser. I would mainly prefer using Stream over String for the result type so the parser may start working before the whole file is downloaded (and the internal parser actually uses streams for URLs now).

The other thing is how to pass the connection manager to jStyleParser. Apart from parsing the style sheets, network connections are also necessary for the `assignDOM()` function that should download and parse the style sheets. So we would have to create new versions of several `parse()` and `assignDOM()` methods. What about configuring the CSSFactory for the given connection manager?

**Comment by hrj** [comment]
Your ideas about Stream-over-String, and using a DocumentSource-like-class seem fine to me.

About the API: Adding it to the CSSFactory would make it a global connection manager, which won't be very useful to gngr. The context of the request would be lost. I think adding more versions of `parse()` and `assignDOM()` might be necessary. However, you could mitigate the problem by adding a single `Config` parameter, that can hold the connection manager and allow more options to be added later. That way, multiple versions won't be required whenever a new requirement comes up, and the existing APIs will continue being supported.

I also have some other questions / ideas.

### Blocking or async
Should the call back be blocking or async? Blocking seems to be sufficient for now; but I haven't fully thought about it. Blocking means thread management will be pushed to the parser client (which might be a good thing).

### Callbacks or Call-forwards
Is it better to avoid call backs and just keep the `@import` rule in the AST? The parser client can then request jStyleParser to update the AST after the first call is over. 

Although it will increase the complexity in the parser client (gngr or cssbox), it would improve performance in some cases. For example, `@import` rules can be filtered via media queries and since the media queries need to be dynamically evaluated (say based on window dimension), it would be more efficient to just apply the `import rules`, rather than reparse the whole CSS again.

But doing this dynamically would mean dynamically attaching rule-blocks to an existing import rule, which means mutable state.

Also, I am not sure, how important it is to optimise for the case of dynamically changing media queries. I don't think it is used that often, but I am not very familiar with the topic.

**Comment by hrj** [comment]
Oh, I just realized: A stream interface would make the question of Blocking or Async moot. As long as the stream is fed, the consumer can be happy. :)

**Comment by hrj** [comment]
I had a re-look at the various media queries, and only `width` and `height` are likely to change very quickly (as a window is resized). I believe, it is rare enough to ignore its performance, for now.

So, IMO, it would be fine to have callbacks with a streaming interface, and thus keep the AST immutable (compared to a call-forward API).

**Comment by radkovo** [comment]
I agree. I have created the corresponding interface in `master` and I have pushed the corresponding API extensions to `network` branch just for the case I am totally wrong at this late hour...

**Comment by hrj** [comment]
@radkovo In my quick tests, the `network` branch works fine. Will confirm fully later. Thanks for the changes!

**Comment by hrj** [comment]
One question: In the `NetworkProcessor` interface, the `fetch` function declares a throws clause. In case of error while fetching, do you prefer `fetch()` implementation to throw `IOException` or to return null? I have a hunch it is the former, but just want to confirm.

**Comment by hrj** [comment]
There are two failure modes in `gngr`:
  * The network connection threw an IOException, which can be propagated from the `fetch` method.
  * The network connection was denied (due to user policy).

If you allow the `fetch` function to return `null` then I can map the second type of failure to `null`. Else, I will map both failures to `IOException`.

For reference, here's how my implementation looks. See the `TODO` comment.

```java
    @Override
    public InputStream fetch(URL url) throws IOException {
      try {
        return AccessController.doPrivileged((PrivilegedExceptionAction<InputStream>) () -> {
          final NetworkRequest request = bcontext.createHttpRequest();
          request.open("GET", url, false);
          request.send(null, new Request(url, RequestKind.CSS));
          final byte[] responseBytes = request.getResponseBytes();
          if (responseBytes == null) {
            return null; // TODO: Request denied. Return null or throw exception?
          } else {
            return new ByteArrayInputStream(responseBytes);
          }
        });
      } catch (final PrivilegedActionException e) {
        if (e.getException() instanceof IOException) {
          throw (IOException) e.getException();
        } else {
          throw new RuntimeException(e);
        }
      }
    }
  }
```

**Comment by radkovo** [comment]
I would prefer throwing an exception in all cases. Generally, different failure scenarios may occur in different implementations and the exceptions allow to distinguish them. Returning null is not so descriptive and must be handled separately.

**Comment by hrj** [comment]
:+1: 
Well said. I will modify my code to throw an exception in both cases.

**Comment by radkovo** [comment]
Ok, merged to master and closing this issue.
