### ISSUE TITLE
DeclarationTransformer cannot be changed due to private constructor

### ISSUE THREAD

**Issue by ChristophKaser** [radkovo/jStyleParser#19]
CSSFactory contains a method registerDeclarationTransformer. However, this method is unusable, because it expects an instance of DeclarationTransformer, which is effectively a final class: It only contains one constructor, which is private. 
If the user should be able to register his own DeclarationTransformer, either a DeclarationTransformer interface has to be introduced (similar to SupportedCSS), or the constructor needs to be changed to protected.

**Comment by radkovo** [comment]
This seems to be fixed by 6dabd5259e492dbad421858cc67d7f7835d47f09 .
