### ISSUE TITLE
Consider using Arrays instead of Lists

### ISSUE THREAD

**Issue by hrj** [radkovo/jStyleParser#28]
### Why
I was profiling gngr, looking at memory allocations. Specifically, I was profiling the browser in interaction mode (after CSS parsing and layouting is done). For example, I open reddit.com, let the browser fully load all resources, finish JS loading, etc. I then start the profiler and hover the mouse over different elements to check the response times.

For such a profile, the largest allocations happen in `AnalyserUtil.hasPseudoSelectorForAncestor` in the [inner for loop](https://github.com/UprootLabs/jStyleParser/blob/i17_quick_hover/src/main/java/cz/vutbr/web/domassign/AnalyzerUtil.java#L200-L204). The allocations are for creating an iterator for the list of selectors!

### Suggestion
If an array is used to store the selectors, then the memory pressure drops significantly. It requires changing just a couple of lines of code. (However, the unit tests require more changes).

Using Arrays may also help in the future, when [value types](https://blogs.oracle.com/jrose/entry/value_types_in_the_vm) land in Java.

Arrays used to be a little cumbersome to use, but with the new streams APIs (`Arrays.toStream()`) and lambda support in Java 8, it is not so bad.

If you are fine with this. I can help make the changes, and send a PR.

**Comment by radkovo** [comment]
Ok, I agree with this. I would be grateful if you could send a PR. Just a note (regarding the array APIs): jStyleParser is still targetted for Java 6. It would be probably possible to move to Java 7 but I mean it's too early for Java 8 : it would be very limiting for such a general purpose library.

**Comment by hrj** [comment]
Closed by PR #31
