### ISSUE TITLE
Consider making MatchingCondition cloneable

### ISSUE THREAD

**Issue by hrj** [radkovo/jStyleParser#30]
After the hover optimisations, we have code like this in gngr:

```java
  if (!mouseOver) {
    elementMatchCondition.addMatch(ancestor, PseudoDeclaration.HOVER);
  }
  final boolean hasMatch = descendent.hasHoverStyle(ancestor);
  if (!mouseOver) {
    elementMatchCondition.removeMatch(ancestor, PseudoDeclaration.HOVER);
  }
  if (hasMatch) {
    descendent.informLocalInvalid();
  }
```
This is because we want to make just one DOM pass, but different calls require different match conditions. The `hasHoverStyle` check requires the `HOVER` while the `informLocalInvalid` require `HOVER` to be absent.

If I could clone the MatchingCondition, my code will get simplified, and optimised:
```
// outside the DOM walk
originalMatchCondition = elementMatchCondition.clone();
originalMatchCondition.addMatch(ancestor, PseudoDeclaration.HOVER);

...
  // inside the DOM walk
  final boolean hasMatch = descendent.hasHoverStyle(ancestor, originalMatchCondition);
  if (hasMatch) {
    descendent.informLocalInvalid();
  }
```

I will send a PR for this soon, assuming you are okay with this change.

**Comment by radkovo** [comment]
I have no problem with this, thanks in advance for the PR.
