### ISSUE TITLE
Parsing shorthand values can result in bad css

### ISSUE THREAD

**Issue by church29** [radkovo/jStyleParser#33]
To reproduce:
Attempt to parse and print 
margin: 2px 0 0 0
Expected Result:
margin: 2px 0 0 0
Actual Result:
margin: 2px000

**Comment by radkovo** [comment]
Hi, I'm not able to reproduce it here. Could you provide a simple test case and jStyleParser version you are using?

**Comment by church29** [comment]
The issue occurs in rule.toString

**Comment by ChristophKaser** [comment]
This was fixed with https://github.com/radkovo/jStyleParser/pull/23
