### ISSUE TITLE
id selectors that begin with a digit shouldn't be applied 

### ISSUE THREAD

**Issue by hrj** [radkovo/jStyleParser#41]
Found this from [a w3c test](https://test.csswg.org/suites/css21_dev/nightly-unstable/xhtml1/id-selector-005.xht):

```
            #1digit
            {
                color: red;
            }
```

This selector shouldn't be applied because it begins with a digit. Note that `1digit` is a valid id in DOM, but not in CSS.

**Comment by radkovo** [comment]
Ok, seems to be fixed.

**Comment by hrj** [comment]
The fix causes a regression elsewhere: https://test.csswg.org/suites/css21_dev/nightly-unstable/xhtml1/ident-012.xht

The CSS:

```css
#\36ident, .four {
    color: green;
}
```

By escaping the number they are expecting it to match.

**Comment by hrj** [comment]
> By escaping the number they are expecting it to match.

Sorry, it is probably the second selector (`.four`) which is matching, which jStyleParser is discarding the whole rule?

**Comment by radkovo** [comment]
I have tested with other browsers and the behavior corresponds to the referenced test case:
- The whole rule should be discarded when the ID selector is invalid (this is ok in jStyleParser)
- However, ID selector with escaped numbers is valid (this is the bug)

I will fix it tomorrow.

**Comment by radkovo** [comment]
Ok, another solution is available. It should pass all the referenced tests.

**Comment by hrj** [comment]
Yes, it passed all tests. Thanks.
