### ISSUE TITLE
An RGB value is invalid if it has both percentages and number assignments.

### ISSUE THREAD

**Issue by hrj** [radkovo/jStyleParser#42]
As per [this test](https://test.csswg.org/suites/css21_dev/nightly-unstable/xhtml1/colors-004.xht)

```
          div {
              color: rgb(100%, 0, 0);
          }
```

is not a valid color rule.

**Comment by radkovo** [comment]
Thanks for reporting. Fixed in master.

**Comment by hrj** [comment]
Works great, and also progresses another test: `color-000.xht`. With no regressions.

Thanks for the quick fix!
