### ISSUE TITLE
z-index absent in nodeData when specified to minimum value - 1

### ISSUE THREAD

**Issue by hrj** [radkovo/jStyleParser#43]
[Test case](https://test.csswg.org/suites/css21_dev/nightly-unstable/xhtml1/z-index-001.xht)

The z-index of `div2` is specified as `-2147483649`. jStyleParser doesn't put any z-index value in corresponding nodeData.

If I understand right, when the z-index is lower than the minimum value, it should get clipped to the minimum value.

Although this might seem like a rare edge-case, I think this might be used not-so-rarely in real websites, to ensure that some element is always rendered behind others.

**Comment by hrj** [comment]
More importantly z-index set to minimum value (-2147483648) doesn't work either :smile:

[Test case](https://test.csswg.org/suites/css21_dev/nightly-unstable/xhtml1/z-index-002.xht)

**Comment by hrj** [comment]
Sorry for the spam; I am going through the tests sequentially, and logging them in that order.

z-index set to maximum value (2147483648) doesn't work too.

[Test case](https://test.csswg.org/suites/css21_dev/nightly-unstable/xhtml1/z-index-012.xht)

**Comment by radkovo** [comment]
Actually CSS specification seems not to define the integer range nor the expected browser behavior when the range is exceeded. From this point of view, I don't like just silently clipping to the maximum/minimum value. However, we should probably keep the standard behavior of other so I implemented the same in jStyleParser.

**Comment by hrj** [comment]
> Actually CSS specification seems not to define the integer range nor the expected browser behavior when the range is exceeded.

I noticed this after reporting this issue: the tests are marked as `optional`. Anyway, glad that this is handled now.

Thanks!
