### ISSUE TITLE
selector with both :before and :after should be rejected

### ISSUE THREAD

**Issue by hrj** [radkovo/jStyleParser#62]
If a selector has both `:before` and `:after` then it should be rejected. For example:

```
#id:before:after {
}
```

The selector should be rejected. I am not sure if the whole rule gets rejected (probably not).

Test-case: https://test.csswg.org/suites/css21_dev/nightly-unstable/xhtml1/before-after-001.xht

**Comment by radkovo** [comment]
Thanks for reporting this. It should be fixed now.

**Comment by hrj** [comment]
Confirmed fix. Thanks!
