### ISSUE TITLE
Sub-string class names are ignored in a class expression

### ISSUE THREAD

**Issue by mb34890** [radkovo/jStyleParser#65]
I have this issue with the Analyzer evaluateDOM() behavior. 

When evaluating a class expression where there are multiple similar class names, only the first occurrence of the "similar" class name is considered. The returned StyleMap will not contain the style attributes of the later occurrences.

Here is an example:

```
<html>
<head>
<style>
.abc {
    background-color: blue;
}

.abcd {
    color: yellow;
}
</style>
</head>
<body>

<h1 class="abcd abc">Some text</h1>

</body>
</html>
```

The "**abc**" class will be completely ignored. Text background will not be applied.
I suspect the issue is that "**abc**" is a sub-string of "**abcd**", but I do not know whether this is a bug or not.

**Comment by mb34890** [comment]
Were you able to reproduce it then? Any workaround I might use?

**Comment by hrj** [comment]
@mb34890 I tried your example in gngr (which uses the jstyleparser's CSS analyser), and I am not able to reproduce this issue. Works fine for me.

**Comment by hrj** [comment]
I deleted my comment. The issue might be present with the specific API that you mentioned.

**Comment by mb34890** [comment]
Were you able to reproduce it then? Any workaround I might use?

**Comment by hrj** [comment]
I didn't try to reproduce it outside of [my code](https://github.com/UprootLabs/gngr/blob/master/src/HTML_Renderer/org/lobobrowser/html/domimpl/HTMLElementImpl.java#L184). But I might be using a different API than you are.

I suggest you create a test-case and make a PR for it. That would make it easy to reproduce and fix.

**Comment by radkovo** [comment]
I tried to reproduce this bug using the BoxBrowser demo app and current CSSBox but everything works as expected (screenshot attached). Are you using the latest CSSBox and did you try to use BoxBrowser with the given example code?
![screenshot_20161106_143848](https://cloud.githubusercontent.com/assets/550349/20038171/26b611ec-a42f-11e6-875c-22ecd360fb3d.png)

**Comment by mb34890** [comment]
Chances are that I'm not using the latest version. I will make a try with latest version soon and post the result.

**Comment by radkovo** [comment]
Closing as not confirmed.
