### ISSUE TITLE
Too many logs

### ISSUE THREAD

**Issue by NatashaKozhevnikova** [radkovo/jStyleParser#66]
Hello! There are too many output logs with styles. Could you turn it off? Or may be make some parametr that will turn log off. Specially too many logs in 
_cz.vutbr.web.csskit.antlr4.SimplePreparator.class_ 
and
_cz.vutbr.web.domassign.DeclarationTransformer.class_.
I can't even watch my logs because there are thounds of lines

**Comment by radkovo** [comment]
jStyleParser uses the log4j API for logging so you should be able to configure logging globally in your application. If you can see the log output, you probably use some log4j implementation (e.g. logback) and you should change the logging settings for the mentioned packages, You may find a sample logback configuration in the attachment that mutes jStyleParser logs completely. For other implementations, you have to consult its documentation for configuration options.

logback.xml (to be put to your classpath)
```
<configuration>

	<appender name="cssbox" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<pattern>%-4relative %-5level %-25logger{1} - %msg%n</pattern>
		</encoder>
	</appender>

	<logger name="org.fit.cssbox" additivity="false">
		<level value="OFF" />
		<appender-ref ref="cssbox" />
	</logger>

	<appender name="jstyleparser" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<pattern>%-4relative %-5level %logger{35} - %msg%n</pattern>
		</encoder>
	</appender>
	
	<logger name="test" additivity="false">
		<level value="OFF" />
		<appender-ref ref="jstyleparser" />
	</logger>

	<logger name="cz.vutbr.web" additivity="false">
		<level value="OFF" />
		<appender-ref ref="jstyleparser" />
	</logger>

	<logger name="cz.vutbr.web.csskit" additivity="false">
		<level value="OFF" />
		<appender-ref ref="jstyleparser" />
	</logger>

	<logger name="cz.vutbr.web.csskit.antlr" additivity="false">
		<level value="OFF" />
		<appender-ref ref="jstyleparser" />
	</logger>

	<logger name="cz.vutbr.web.domassign" additivity="false">
		<level value="OFF" />
		<appender-ref ref="jstyleparser" />
	</logger>

	<logger name="cz.vutbr.web.domassign.DeclarationTransformer" additivity="false">
		<level value="OFF" />
		<appender-ref ref="jstyleparser" />
	</logger>

	<logger name="org.fit.segm" additivity="false">
		<level value="warn" />
		<appender-ref ref="cssbox" />
	</logger>
	
	<logger name="org.fit.layout" additivity="false">
		<level value="trace" />
		<appender-ref ref="cssbox" />
	</logger>

	<logger name="org.openrdf" additivity="false">
		<level value="OFF" />
		<appender-ref ref="cssbox" />
	</logger>

	<root>
		<appender-ref ref="cssbox" />
	</root>

</configuration>
```

**Comment by mirraj2** [comment]
generally speaking it's not very developer friendly to force them to have to create a whole file just to turn off logging.  You are also assuming that everyone is familiar with the ins and outs of log4j

**Comment by mirraj2** [comment]
I fixed this by putting this at the beginning of my program:  System.setProperty("org.slf4j.simpleLogger.log.cz.vutbr.web.csskit", "warn");
