### ISSUE TITLE
Performance of CSSToken/TypeMapper

### ISSUE THREAD

**Issue by lambdaupb** [radkovo/jStyleParser#68]
I just did some performance eval with this library and the `TypeMapper` creation dominates my sampling (which could deceive me). Maybe it could be created in `CSSTokenFactory` retained there and passed to the `CSSToken` constructor instead of the constructor of `CSSToken` creating one for itself each time.

`TypeMapper` seems to be immutable once constructed anyway.

**Comment by radkovo** [comment]
Many thanks for pointing this out. I have implemented the solution you proposed and after a few experiments it seems to improve the parser performance by about 20-25%. Any other proposals like this are welcome.

**Comment by lambdaupb** [comment]
Thanks for fixing it so quickly :)
