### ISSUE TITLE
Animation-delay negative value

### ISSUE THREAD

**Issue by nicoloboschi** [radkovo/jStyleParser#72]
Hello, 
I think i found a bug on parsing css string containing html code, with animation delay rule set up with negative value.
Html code: 
```
<html>
    <head>
        <style> 
            div {
                animation-delay: -1s;
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div></div>
    </body>
</html>
```

When i parse it, only text-align rule is parsed.

Java code: 
```
StyleSheet stylesheet = CSSFactory.parseString(css, null);
for (Rule<?> rule : stylesheet) {
            if (!(rule instanceof RuleSet)) {
                continue;
            }
            RuleSet ruleset = (RuleSet) rule;
            System.out.println("ruleset:" + ruleset);
        }
```

**Note: using positive numbers or zero in animation delay, the rule block is correctly created.**

I used 2.1 version.

**Comment by hrj** [comment]
(I am not the maintainer of this repo; just a contributor)

It doesn't look like css3 animations are stably defined yet. They are still in the draft stage : https://www.w3.org/TR/css3-animations/

That said, I wonder whether un-recognized css properties are also expected to be visible in the ruleset?

**Comment by radkovo** [comment]
Negative time values have been allowed by [this commit](https://github.com/radkovo/jStyleParser/commit/14a246bacd8a2f10013dcd15354f04e365289b64) which is not contained in 2.1. You may try to use the git version if it works for you. It should be stable at the moment. However, the animation-related properties are not supported yet so they will be probably ignored anyway.

**Comment by nicoloboschi** [comment]
@radkovo Thank you, is there a new release programmed soon?

**Comment by nicoloboschi** [comment]
Great, with 3.0 release this issue has been fixed!
