### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by hameno** [radkovo/jStyleParser#76]
Hello,
I'm trying to use this library on Android but unfortunately we cannot use java.awt.Color and the current version 3.0 will crash when parsing a stylesheet with colors: 
```NoClassDefFoundError: Failed resolution of: Ljava/awt/Color;```
Is there any way to make this library independent on java.awt.* classes?

Also regarding the License: If we can fix the above issue, would it be okay to use this library in a commercial, closed-source application? We would of course mention and link to your site in our information screen.

**Comment by radkovo** [comment]
Actually, java.awt classes are not used frequently in the project. I mean I could easily replace Color with our own implementation if it helps. It's a good idea to make the library Android-compatible.

Regarding the license: if you fix a bug in the library itself, you should make the fixed version available under the same (LGPL) license. However, the application may remain closed-source; this is allowed by LGPL.

**Comment by hameno** [comment]
Okay, thats great. I was going to try to fix that in the next hours - I will provide a PR for that, okay?

**Comment by radkovo** [comment]
Ok, great. Thanks!

**Comment by hameno** [comment]
Okay, replacement of java.awt.Color is done, unfortunately I have found a new problem: 
NoClassDefFoundError: Failed resolution of: Lorg/w3c/dom/traversal/DocumentTraversal;

I'm going to try to fix that too

**Comment by hameno** [comment]
Okay, it looks like manually including those interfaces to the app project seems to work. 

org.w3c.dom.traversal.DocumentTraversal
org.w3c.dom.traversal.NodeFilter
org.w3c.dom.traversal.NodeIterator
org.w3c.dom.traversal.TreeWalker

Any idea on how fix that for every user of this library? I'm not sure if we can include the package (and subpackages) org.w3c.dom.* since they are partially available in android

**Comment by radkovo** [comment]
I mean these interfaces should not be part of the library itself; they could conflict with standard XML parser implementations. Could be a solution to create a separate library providing these packages and use is as a dependency on Android only? Or does something like that even exist?

**Comment by hameno** [comment]
Okay, now that the PR is merged, could you perform a new release? For the missing interfaces we could add a Wiki entry with information on how to include those into android projects.

**Comment by radkovo** [comment]
Ok, 3.1 has been just released. Many thanks for your contribution!

**Comment by hameno** [comment]
👍
