### ISSUE TITLE
Gradients are not parsed correctly

### ISSUE THREAD

**Issue by Mangara** [radkovo/jStyleParser#88]
Arguments to the `linear-gradient` style are not parsed correctly. For example, the following gradient: 

    linear-gradient(to bottom, rgb(245,245,245) 0%, rgb(221,221,221) 100%)

After parsing and pretty-printing turns into

    linear-gradient(tobottom,0.0%,100.0%)

**Comment by radkovo** [comment]
It seems that nested functions are broken, namely the `CSSParserVisitorImpl.visitFuct()` works directly with terms_stack and thus it is not prepared to work in the functArgs context. I will try to refactor this part (+ better output formatting of function args is necessary).

**Comment by Mangara** [comment]
Hashes don't seem to work either. For example, `linear-gradient(#FF0033, #3300FF)` is printed as `linear-gradient(,)`.

**Comment by Mangara** [comment]
I won't have time to work on this more today, so I'll make a PR for the test and let you look into it. Should I add ignore directives to failing tests, or just let them fail?

**Comment by radkovo** [comment]
Ok, hashes should be fixed by [this commit](https://github.com/radkovo/jStyleParser/commit/0fd9e7e8fcaa374971d16cace9bbc0b708454537). Functions will take more time.

**Comment by radkovo** [comment]
Ad tests: just let them fail. Hopefully the fix won't take too long.

**Comment by radkovo** [comment]
All tests are passing now.

**Comment by Mangara** [comment]
Thanks for being so responsive and receptive to these!
